spring:
  datasource:
    url: jdbc:mysql://192.168.118.132:3306/user?characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver